# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: NPM Angular
  inputs:
    command: 'custom'
    customCommand: 'install @angular/cli@7.3.1'

- task: Npm@1
  displayName: NPM Install
  inputs:
    command: 'install'

- task: Npm@1
  displayName: NPM Build
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'werfklas'
    publishLocation: 'Container'