# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: NPM Angular
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@13.2.2'

# - task: Npm@1
#   displayName: NPM Install
#   inputs:
#     command: 'install'

# - script: |
#     npm run build
#   displayName: NPM Build

- script: |
    ./mvnw -Pprod clean verify

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    flattenFolders: true
    SourceFolder: '$(system.defaultworkingdirectory)/target'
    Contents: |
      *.*
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'werfklas'
    publishLocation: 'Container'
